
package AngryCats;

import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author Mechu
 */
public class FrameJuego extends javax.swing.JDialog {

    public FrameJuego() {
        //super();
        
        setTitle("Jugar Angry Cats");
        setVisible(true);
        setSize(1200, 700);
        setResizable(false);
        setLocationRelativeTo(null);
        
        VistaJugar miLayer= new VistaJugar();
        miLayer.iniciarJuego();
        
        
        miLayer.addComponentListener(new ComponentListener()
        {
            @Override
            public void componentResized(ComponentEvent e)
            {
              
            }

            @Override
            public void componentMoved(ComponentEvent e)
            {
             
            }

            @Override
            public void componentShown(ComponentEvent e)
            {
             
            }

            @Override
            public void componentHidden(ComponentEvent e)
            {
                setVisible(false);
                dispose();
            }
        });

        add(miLayer);
        
    }
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     * @param
     
    
         Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
 */